apigest/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("gestruc/", include("gestruc.urls", namespace="gestruc")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

    # urlpatterns += [
    #     url(r'^__debug__/', include(debug_toolbar.urls)),
    # ]

gestruc/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls import include, url
from . import views
# from gestruc.views import ColoniesUpdate
# from django.views.generic import TemplateView, ListView
import debug_toolbar

app_name = 'gestruc'

urlpatterns = [
    path("", views.index, name="index"),
    path('__debug__/', include(debug_toolbar.urls)),
    path("ruchers/", views.ruchers_list, name="ruchers_list"),
    path("miellerie/", views.miellerie, name="miellerie"),
    path("interventions/", views.interventions, name="interventions"),
    path("validation/", views.validation, name="validation"),
    path("ruchers/<int:pk>/", views.rucher_detail, name="rucher_detail"),
    path("ruchers/add/", views.RuchersCreateView.as_view(), name="rucher_add"),
    path("ruchers/<int:pk>/edit/", views.rucher_update, name="rucher_update"),
    path("ruchers/<int:pk>/del/", views.rucher_delete, name="rucher_delete"),
    path("ruches/<int:pk>/", views.ruche_detail, name="ruche_detail"),
    path("ruches/<int:pk>/edit/", views.RuchesUpdate.as_view(), name='ruche_edit'),
    path("ruches/add/", views.RuchesCreate.as_view(), name='ruche_add'),
    path("colonies/", views.ColoniesList.as_view(), name="colonies"),
    path("colonies/add/", views.ColoniesCreateView.as_view(), name="colonie_add"),
    path("colonies/<int:pk>/", views.colonie_detail, name="colonies_detail"),
    path("colonies/<int:pk>/edit", views.ColoniesUpdate.as_view(), name='colonies_edit'),
    path("ruches/", views.ruches_list, name="ruches"),
    path("colonies/add", views.ColoniesCreateView.as_view(), name="colonie_add"),
    path("visites/", views.visites_list, name="visites"),
    path("visites/<int:pk>/", views.visite_detail, name="visite_detail"),
    path("visites/add/", views.VisiteCreateView.as_view(), name="visite_add"),
    path(
        "visites/ajax/load-affectation/",
        views.load_affectation,
        name="ajax_load_affectation",
    ),
    path("sites/", views.SiteListView.as_view(), name="sites_list"),
    path("sites/add/", views.SiteCreateView.as_view(), name="site_add"),
    path("sites/<int:pk>/", views.SiteUpdateView.as_view(), name="site_update"),
    path("sites/ajax/load-communes/", views.load_communes, name="ajax_load_communes"),
    path("ruchers/ajax/load-communes/", views.load_communes, name="ajax_load_communes"),
    path("partenaires/ajax/load-codepostal/", views.load_codepostal, name="ajax_load_codepostal"),
    path("affectations/", views.aff_list, name="aff_list"),
    path("affectations/all/", views.aff_hist, name="aff_hist"),
    path(
        "affectations/<int:pk>/",
        views.aff_ruruchcol_detail,
        name="aff_ruruchcol_detail",
    ),
    path("affectations/add/", views.aff_ruruchcol_create, name="aff_ruruchcol_add"),
    path("affectations/<int:pk>/del/", views.aff_ruruchcol_delete, name="aff_del"),
    path("affectations/<int:pk>/fin/", views.aff_ruruchcol_fin, name="aff_fin"),
    path("interventions/", views.interventions, name="interventions"),
    path(
        "interventions/ajax/load-affectation/",
        views.load_affectation,
        name="ajax_load_affectation",
    ),
    path("interventions/add/", views.IntervCreateView.as_view(), name="interv_add"),
    path(
        "interventions/nourrissement/list",
        views.nour_list,
        name="nour_list"
    ),
    path(
        "interventions/nourrissement/add/",
        views.NourrissementCreate.as_view(),
        name="nour_add",
    ),
    path(
        "interventions/nourrissement/<int:pk>/",
        views.nour_detail,
        name="nour_detail",
    ),
    path("interventions/essaim", views.essaim, name="essaim"),
    path("interventions/mvt_cadres", views.mvt_cadres, name="mvt_cadres"),
    path("interventions/varroa", views.varroa, name="varroa"),
    path("interventions/recolte", views.recolte, name="recolte"),
    path("partenaires/", views.PartenaireListView.as_view(), name="partenaires_list"),
    path("partenaires/add/", views.PartenaireCreateView.as_view(), name="partenaire_add"),

]

gestruc/models.py
from django.db import models
from django.contrib.gis.db import models
import datetime
from django.utils import timezone
from django.urls import reverse


class Departement(models.Model):
    insee_dep = models.CharField(primary_key=True, max_length=3, blank=True, null=False)
    nom_dep_m = models.CharField(max_length=50, blank=True, null=True)
    nom_dep = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        ordering = ["nom_dep_m"]

    def __str__(self):
        return self.nom_dep_m


class Commune(models.Model):
    insee_com = models.CharField(primary_key=True, max_length=5, blank=True, null=False)
    insee_dep = models.ForeignKey(Departement, on_delete=models.CASCADE)
    nom_com_m = models.CharField(max_length=50, blank=True, null=True)
    nom_com = models.CharField(max_length=45, blank=True, null=True)
    # commentaire = models.TextField(max_length=200, blank=True, null=True)

    class Meta:
        ordering = ["nom_com_m"]

    def __str__(self):
        return self.nom_com_m


class Codpostal(models.Model):
    insee_com = models.CharField(primary_key=True, max_length=5, blank=True, null=False)
    nom_com_m = models.CharField(max_length=50, blank=True, null=False)
    cod_post = models.CharField(max_length=5, blank=True, null=False)
    lat_lon = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ["nom_com_m"]

    def __str__(self):
        return self.nom_com_m


class Site(models.Model):
    nom_site = models.CharField(max_length=50, blank=True, null=True)
    code_site = models.CharField(max_length=20, blank=True, null=True)
    departement = models.ForeignKey(
        Departement, on_delete=models.CASCADE, blank=True, null=True
    )
    commune = models.ForeignKey(
        Commune, on_delete=models.CASCADE, blank=True, null=True
    )

    def __str__(self):
        return self.nom_site


class Typ_part(models.Model):

    type_partenaire = models.CharField(max_length=50, blank=True, null=True)
    commentaire = models.TextField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.type_partenaire


class Partenaire(models.Model):
    typ_part =  models.ForeignKey(
        Typ_part, on_delete=models.CASCADE, blank=True, null=True
    )
    nom = models.CharField(max_length=50, blank=True, null=True)
    representant = models.CharField(max_length=50, blank=True, null=True)
    adr1 = models.CharField(max_length=50, blank=True, null=True)
    adr2 = models.CharField(max_length=50, blank=True, null=True)
    comcp = models.ForeignKey(
    Codpostal, on_delete=models.CASCADE, blank=True, null=True
    )
    tel = models.CharField(max_length=20, blank=True, null=True)
    gsm = models.CharField(max_length=20, blank=True, null=True)
    mail = models.EmailField(max_length=100, blank=True, null=True)
    commentaire = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.nom


class Ruchers(models.Model):
    nom_rucher = models.CharField(max_length=25, default='NOM DU RUCHER', blank=True, null=False)
    code_rucher = models.CharField(max_length=20, default='CODE DU RUCHER', blank=True, null=True)
    departement = models.ForeignKey(
        Departement, on_delete=models.CASCADE, blank=True, null=True
    )
    commune = models.ForeignKey(
        Commune, on_delete=models.CASCADE, blank=True, null=True
    )
    lieudit = models.CharField(max_length=50,default='NOM DU LIEU-DIT', blank=True, null=False)
    proprio = models.CharField(max_length=25, blank= True, null=False)
    loyer = models.CharField(max_length=25, blank= True, null=False)
    statut_rucher = models.BooleanField(blank=True, null=False, default=True)
    bio = models.BooleanField(blank=True, null=False, default=True)
    geom = models.PointField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("gestruc:rucher-detail", kwargs={"pk": str(self.pk)})

    def __str__(self):
        return self.nom_rucher


class Typ_ruche(models.Model):
    type = models.CharField(max_length=30, blank=False, null=False)
    modele = models.CharField(max_length=30, blank=True, null=True)
    description = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.modele


class Ruches(models.Model):
    code_ruche = models.CharField(max_length=10, blank=False, null=False, unique=True)
    type_ruche = models.ForeignKey(
        Typ_ruche, on_delete=models.CASCADE, blank=True, null=False
    )
    date_mes = models.DateField(("Date mise en service"), default=datetime.date.today)
    statut_bio = models.BooleanField(blank=True, null=False, default=False)
    # affectation = models.BooleanField(default=False)
    commentaire = models.TextField(max_length=200, blank=True, null=True)

    def get_absolute_url(self):
        return reverse("gestruc:ruche_detail", kwargs={"pk": str(self.pk)})

    def __str__(self):
        return self.code_ruche


class Note_etat(models.Model):
    note = models.CharField(max_length=2)
    description = models.TextField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.description


class Phenotypes(models.Model):
    phenotype = models.CharField(max_length=10, blank=True, null=True)
    description = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.phenotype


class Note_agress(models.Model):
    note = models.CharField(max_length=2)
    description = models.TextField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.description


class Note_essaim(models.Model):
    note = models.CharField(max_length=2)
    description = models.TextField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.description


class Note_prod(models.Model):
    note = models.CharField(max_length=2)
    description = models.TextField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.description


class Note_varroa(models.Model):
    note = models.CharField(max_length=2)
    description = models.TextField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.description

class Issu_de(models.Model):
    issude = models.CharField(max_length=20)

    def __str__(self):
        return self.issude

class Colonies(models.Model):
    code_col = models.CharField(max_length=20, blank=True, null=False, unique=True)
    annee_reine = models.CharField(
        max_length=4, blank=False, null=True
    )
    phenotype = models.ForeignKey(Phenotypes, on_delete=models.CASCADE, null=True)
    issu_de = models.ForeignKey(Issu_de, on_delete=models.CASCADE, null=True)
#    agressivite = models.ForeignKey(Note_agress, on_delete=models.CASCADE)
#    essaimage = models.ForeignKey(Note_essaim, on_delete=models.CASCADE)
#    production = models.ForeignKey(Note_prod, on_delete=models.CASCADE)
#    varroa = models.ForeignKey(Note_varroa, on_delete=models.CASCADE)
    existante = models.BooleanField(default=True)
#    affectation = models.BooleanField(default=False)
    commentaire = models.TextField(max_length=200, blank=True, null=True)

    def get_absolute_url(self):
        return reverse("gestruc:colonies_detail", kwargs={"pk": str(self.pk)})

    def __str__(self):
        return self.code_col


class Ruruchcol(models.Model):
    rucher = models.ForeignKey(
        Ruchers, related_name="rucher", on_delete=models.CASCADE, null=False
    )
    ruche = models.ForeignKey(
        Ruches, related_name="ruche", on_delete=models.CASCADE, null=False
    )
    ruche_vide =models.BooleanField(default=True)
    colonie = models.ForeignKey(
        Colonies, related_name="colonie", on_delete=models.CASCADE, null=False, default=11
    )
    emplacement = models.CharField(max_length=10, blank=True, null=True)
    debut = models.DateTimeField("Date début")
    fin = models.DateTimeField("Date de fin", blank=True, null=True)
    commentaire = models.TextField(max_length=240, blank=True, null=True)

    def ruruchcol_encours(self):
        return self.objects.filter(fin__isnull=True)

    def get_absolute_url(self):
        return reverse("gestruc:Affruruchcol_detail", kwargs={"pk": str(self.pk)})

    def __str__(self):
        return "ruche={0}, colonie={1}".format(
            self.ruche.code_ruche, self.colonie.code_col
        )
        # return 'rucher={0}, ruche={1}, colonie={2}'.format(self.rucher.nom_rucher, self.ruche.code_ruche, self.colonie.code_col)


class Operateur(models.Model):
    pseudo = models.CharField(max_length=20)
    nom = models.CharField(max_length=20, blank=True, null=True)
    prenom = models.CharField(max_length=20, blank=True, null=True)
    infos = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.pseudo


class Typ_visite(models.Model):
    lib_visit = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.lib_visit


class Motif_visite(models.Model):
    lib_motif = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.lib_motif


class Etat_ponte(models.Model):
    note = models.CharField(max_length=2)
    description = models.TextField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.description


class Etat_couv_ouvert(models.Model):
    note = models.CharField(max_length=2)
    description = models.TextField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.description


class Etat_couv_ferme(models.Model):
    note = models.CharField(max_length=2)
    description = models.TextField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.description

gestruc/templates/gestruc/VisiteDetailForm.html
{% extends 'gestruc/base.html' %}

{% block content %}

<H2> It works </H2>
<H1> Detail de la visite n° {{visite.id}} </H1>

<form method="get">

    {{ form.as_p }}


</form>

{% endblock %}

gestruc/templates/gestruc/aff_hist.html
{% extends 'gestruc/base.html' %}

{% block content %}

<h2>Historique des affectations ruchers - ruches - colonies : </h2><br>

  {% if affhist|length_is:"0" %}
    <div class="test-center">
      Nous ne trouvons aucun résultat à cette requête, veuillez essayer de nouveau avec d'autres paramètres de recherche.
    </div>

  {% else %}
    <b>
      <div class="table-responsive-md">
        <div style="height: 600px;overflow: scroll;">
           <table class="table table-light table-striped">
                  <thead class="table-dark">
                    <tr>
                      <th>Id</th>
                      <th>Rucher</th>
                      <th>Ruche</th>
                      <th>Colonie</th>
                      <th>Début</th>
                      <th>Fin</th>
                    </tr>
                  </thead>

                  <tbody>
                  {% for aff in affhist %}
                    <tr>
                      <td><a href="{% url 'gestruc:aff_ruruchcol_detail' aff.id %}">{{ aff.id}}</a></td>
                      <td><a href="{% url 'gestruc:rucher_detail' aff.rucher_id %}">{{ aff.rucher}}</a></td>
                      <td><a href="{% url 'gestruc:ruche_detail' aff.ruche_id %}">{{ aff.ruche}}</a></td>
                      <td><a href="{% url 'gestruc:colonies_detail' aff.colonie_id %}">{{ aff.colonie}}</a></td>
                      <td>{{ aff.debut }}</td>
                      <td>{{ aff.fin }}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
           </table>
        </div>
      </div>
    </b>
  {% endif %}

  <nav>
      <ul class="nav justify-content-center">
        <li class="nav-item lead"><a class="nav-link" href="{% url 'gestruc:aff_list' %}"><button type="button" class="btn btn-dark btn-sm">Affectations en cours</button></a></li>
        <li class="nav-item lead"><a class="nav-link" href="{% url 'gestruc:ruchers_list' %}"><button type="button" class="btn btn-dark btn-sm">Ruchers</button></a></li>
      </ul>
  </nav>



{% endblock %}

gestruc/templates/gestruc/aff_ruruchcol_confirm_delete.html
{% extends 'gestruc/base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <h2>Etes-vous sûr de vouloir supprimer l'affectation "{{ object }}" et toutes les données associées ?</h2>
    <input type="submit" value="Confirmer">
</form>



{% endblock %}

gestruc/templates/gestruc/colonie_detail.html
{% extends 'gestruc/base.html' %}

{% block content %}

<H1> Detail d'une colonie </H1>

<form method="get">
  {% csrf_token %}

     {{ form.as_table }}

<H3>Historique des ruches/ruchers occupés:</H3>

  <ul>
    {% for r in ruchcol %}
        <li>
          <a href="{% url 'gestruc:ruche_detail' r.ruche_id %}">{{ r.ruche }}
          </a>

          <a href="{% url 'gestruc:rucher_detail' r.rucher_id %}">{{ r.rucher }}
          </a>
          ---{{ r.debut }} >>{{ r.fin }}
        </li>
    {% endfor %}

</form>

<nav>
        <ul class="nav justify-content-center">
          <li class="nav-item lead"><a class="nav-link" href="{% url 'gestruc:colonies' %}"><button type="button" class="btn btn-success btn-sm">Retour...</button></a></li>
          <li class="nav-item lead"><a class="nav-link" href="{% url 'gestruc:ruchers_list' %}"><button type="button" class="btn btn-dark btn-sm">RUCHERS</button></a></li>
          <li class="nav-item lead"><a class="nav-link" href="{% url 'gestruc:aff_list' %}"><button type="button" class="btn btn-dark btn-sm">AFFECTATIONS</button></a></li>
        </ul>
      </nav>

<!--<nav id="MenuChoix">
    <ul>
        <li><a href="{% url 'gestruc:ruchers_list' %}"> Retour à la liste des ruchers</a></li>
        <li><a href="{% url 'gestruc:aff_list' %}"> Retour à la liste des affectations </a></li>
    </ul>
</nav>-->


{% endblock %}

gestruc/templates/gestruc/colonies_create_form.html
{% extends 'gestruc/base.html' %}

{% block content %}

  <h2>CRREATION D'UNE COLONIE</h2>

  <form method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Enregistrer</button>
    <a href="{% url 'gestruc:colonies' %}">Ignorer</a>


  </form>



{% endblock %}

gestruc/templates/gestruc/colonies_list.html
{% extends 'gestruc/base.html' %}


{% block content %}
    <h2>LES COLONIES</h2>

        <div class="table-responsive-md">
          <div style="height: 600px;overflow: scroll;">
            <table class="table table-striped table-light">

               <thead class="table-dark">
                  <tr>
                    <th>Id</th>
                    <th>Code Colonie</th>
                    <th>Année reine</th>
                    <th>Phenotype</th>
                    <th>Issue de</th>
                    <th>Existante</th>
                    <th>Modifier</th>
                  </tr>
                </thead>

                <tbody>

            {% for C in colonies %}
                  <tr>
                    <td><a href="{% url 'gestruc:colonies_detail' C.id %}"> {{C.id}}</a></td>
                    <td><a href="{% url 'gestruc:colonies_detail' C.id %}">{{ C.code_col}}</a></td>
                    <td>{{C.annee_reine}}</td>
                    <td>{{C.phenotype}}</td>
                    <td>{{C.issu_de}}</td>
                    <td>{{C.existante}}</td>
                    <td><a href="{% url 'gestruc:colonies_edit' C.id %}"><button type="button" class="btn btn-secondary btn-sm">MODIFIER</button></a>
                  </tr>

            {% endfor %}

                </tbody>
            </table>
          </div>
        </div>

<!--

<a href="{% url 'gestruc:colonie_add' %}"><button type="button" class="btn btn-success mb-2">Créer colonie</button> </a>
<a href="{% url 'gestruc:ruchers_list' %}"><button type="button" class="btn btn-secondary mb-2">Retour</button> </a>
-->
      <nav>
        <ul class="nav justify-content-center">
          <li class="nav-item lead"><a class="nav-link" href="{% url 'gestruc:colonie_add' %}"><button type="button" class="btn btn-dark btn-sm">Créer colonie</button></a></li>
          <li class="nav-item lead"><a class="nav-link" href="{% url 'gestruc:ruchers_list' %}"><button type="button" class="btn btn-dark btn-sm">Retour</button></a></li>
        </ul>
      </nav>

{% endblock %}

{% block content1 %}



{% endblock %}

gestruc/templates/gestruc/commcp_dropdown_list_options.html
<!doctype html>
<html>
    <head>

{% load static %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src={% static 'js/select2.min.js'  type='text/javascript' %} ></script>
    <link href={% static 'css/select2.min.css' rel='stylesheet' type='text/css'%} >

    </head>
    <body>
        <select id='selCom' style='width: 200px;'>
            <option value=" ">---------</option>
            {% for com in commcp %}
            <option value="{{ com.pk }}">{{ com.nom_com_m }} - {{ com.cod_post}}</option>
            {% endfor %}
        </select>

        <input type='button' value='Selected option' id='but_read'>

        <br/>
        <div id='result'></div>

        <!-- Script -->
        <script>
        $(document).ready(function(){

            // Initialize select2
            $("#selCom").select2();

            // Read selected option
            $('#but_read').click(function(){
                var comname = $('#selCom option:selected').text();
                var comid = $('#selCom').val();

                $('#result').html("id : " + comid + ", name : " + comname);
            });
        });
        </script>

    </body>
</html>

gestruc/templates/gestruc/index.html
{% extends 'gestruc/base.html' %}


{% block content %}

  <h3 >les dernières visites réalisées </h3>
        {% if visites|length_is:"0" %}
            <div class="test-center">
              <b> Aucune visite enregistrée </b>
            </div>


        {% else %}

<!--            <ul>-->
<!--                {% for v in visites %}-->
<!--                  <li>-->
<!--                      <a href="{% url 'gestruc:visite_detail' v.id %}"> {{ v.id }}  -  {{ v.datevis }}  {{v.rucher}}-->
<!--                      </a>-->
<!--                  </li>-->
<!--                {% endfor %}-->
<!--            </ul>-->


          <div class="table-responsive-md">
               <table class="table table-striped table-light">
                      <thead class=thead-dark>
                        <tr>
                          <th>#</th>
                          <th>Date visite</th>
                          <th>Code visite</th>
                          <th>Rucher</th>
                          <th>Motif Vis.</th>
                        </tr>
                      </thead>


                      <tbody>

                      {% for v in visites %}
                        <tr>
                          <td><a href="{% url 'gestruc:visite_detail' v.id %}">{{ v.id}}</a></td>
                          <td>{{ v.datevis}}</td>
                          <td><a href="{% url 'gestruc:visite_detail' v.id %}">{{ v.ide_visit}}</a></td>
                          <td>{{ v.rucher}}</td>
                          <td>{{ v.motif_visite}}</td>

                        </tr>

                      {% endfor %}

                        </tbody>
               </table>

          </div>

        {% endif %}

  <h3 >les prochaines visites programmées </h3>

  {% if visprog|length_is:"0" %}
    <div class="test-center">
      Aucune action programmée
    </div>

  {% else %}

          <div class="table-responsive-md">
               <table class="table table-striped table-light">
                      <thead class=thead-dark>
                        <tr>
                          <th>Visit init.</th>
                          <th>Date</th>
                          <th>Rucher</th>
                          <th>Action prog.</th>
                          <th>Commentaire</th>
                        </tr>
                      </thead>


                      <tbody>

                      {% for vp in visprog %}
                        <tr>
                          <td><a href="{% url 'gestruc:visite_detail' vp.id %}">{{ vp.id}}</a></td>
                          <td>{{ vp.dateprog}}</td>
                          <td>{{ vp.rucher}}</td>
                          <td>{{ vp.actionprog}}</td>
                          <td>{{ vp.commentaire}}</td>
                        </tr>

                      {% endfor %}

                        </tbody>
               </table>

          </div>

{% endif %}


{% endblock %}

gestruc/templates/gestruc/interv_form.html
{% extends 'gestruc/base.html' %}

{% block content %}

  <h2>formulaire INTERVENTIONS</h2>

  <form method="post" id="IntervForm" data-interv-url="{% url 'gestruc:ajax_load_affectation' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Enregistrer</button>
    <a href="{% url 'gestruc:interventions' %}">Ignorer</a>
  </form>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <script>
    $("#id_rucher").change(function () {
      var url = $("#IntervForm").attr("data-interv-url");  // get the url of the `load_cities` view
      var rucherId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'rucher': rucherId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_affectation").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

gestruc/templates/gestruc/openlayers-osm.html
{% extends "gis/openlayers.html" %}
{% load l10n %}

{% block options %}{{ block.super }}
options['default_lon'] = {{ 450400 }};
options['default_lat'] = {{ 6754300 }};
options['default_zoom'] = {{ 12 }};
{% endblock %}

{% block base_layer %}
var base_layer = new ol.layer.Tile({source: new ol.source.OSM()});
{% endblock %}

gestruc/templates/gestruc/remerage.html
{% extends 'gestruc/base.html' %}

{% block content %}

<class="intro-text text-center"><h2>Vous êtes sur la page Remerage</h2></h2>



{% endblock %}

gestruc/templates/gestruc/site_form.html
{% extends 'gestruc/base.html' %}

{% block content %}

  <h2>formulaire SITES</h2>

  <form method="post" id="siteForm" data-communes-url="{% url 'gestruc:ajax_load_communes' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Enregistrer</button>
    <a href="{% url 'gestruc:sites_list' %}">Ignorer</a>
  </form>

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <script>
    $("#id_departement").change(function () {
      var url = $("#siteForm").attr("data-communes-url");  // get the url of the `load_cities` view
      var departementId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'departement': departementId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_commune").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

gestruc/templates/gestruc/site_list.html
{% extends 'gestruc/base.html' %}

{% block content %}

<class="intro-text text-center"><h2>Vous êtes sur la page des SITES</h2></h2>



{% endblock %}

gestruc/templates/gestruc/varroa.html
{% extends 'gestruc/base.html' %}

{% block content %}

<class="intro-text text-center"><h2>Vous êtes sur la page Lutte contre le varroa</h2></h2>

<a href="{% url 'gestruc:interventions' %}">retour</a>


{% endblock %}